# Website title and description
# It will appear on home page, in your document head meta (for
# Google search results) and in your feed.xml site description."
name: Deutsch für Algernon
description: "Verschiedene Notizen über deutscher Sprache. Für Alle, auf Deutsch."
cover: 'assets/images/b2.jpg'

# Single author mode. If enabled, 'author' description is used everywhere, author page is disabled.
# Otherwise, edit authors in _data/authors.yml
single_author: true
author:
  id: aufdeutsch
  name: Deutsch für Algernon
  bio: Verschiedene Notizen über Deutsche Sprache. Für Alle, auf Deutsch.
  location: Darmstadt, Germany
  image: assets/images/Ampelmann.png
  url: http://aufdeutsch.github.io

# Edit baseurl to simply '/' if using as your personal page (for project page, use /projectname/)
# edit url to your site full url, e.g. http://yourname.github.io/ (for personal page) or http://yourname.github.io/projectname/
# don't forget the trailing slash
baseurl: /
url: http://aufdeutsch.github.io/

# ID for Google analytics, leave as '-' to turn it off
google_analytics: 'UA-75106109-1'
# Username for disqus comments, leave as '-' to turn them off
disqus: 'aufdeutschgithubio'

# Jykell configuration, edit only if necessary
markdown: kramdown
pagination: 5
permalink: /:title

# Internal, don't edit it
exclude: [
sh.png,
Gemfile,
Gemfile.lock,
README.md
]

